### ISSUE TITLE
Exception not caught: broken cached binary path file

### ISSUE THREAD

**Issue by locallycompact** [neovimhaskell/nvim-hs#92] opened 2021-08-30 13:59 UTC
Also getting this when I open vim

```
Error detected while processing function nvimhs#start[2]..<SNR>11_readCachedBinPaths:
line    9:
E605: Exception not caught: broken cached binary path file
Error detected while processing function nvimhs#start:
line    2:
E171: Missing :endif
```

**Comment by saep** [comment] 2021-08-31 16:57
Probably caused by #91

**Comment by saep** [comment] 2021-09-26 13:45
If this still happens with the latest version (2.1.0.7 or master) , please tell me how to reproduce this.

**Comment by saep** [comment] 2022-11-06 21:02
I'm closing this because I cannot reproduce this and no additional information has been provided for over a year.

**Closed by saep** 2022-11-06 21:02 UTC
Labels: bug, needs info
